### PR TITLE
Add completed basket listing as input.txt for izneo_get

### PR DESCRIPTION
**Pull request by prahal**
This enable one to download the albums in a checkout by its checkout ID (which is alwo the url shown when cehckout complete).

This url can be reconstructed from the checkout ID. For checkout ID 1020304 the url is:
https://www.izneo.com/fr/panier-fin/1020304

### CODE REVIEW

**Comment by prahal** [comment]
Note that I did not implement paging. I have no checkout with paging on the panier-fini page. I don't even know if this page does any paging though I guess it does.

**Comment by prahal** [comment]
@izneo-get the checkout ID is indeed indefinitely available ...
You can access the checkout completion after the checkout is completed and if you did not keep the URL, you can guess it from the profile "Moyens de paiement " https://www.izneo.com/fr/settings/methods then on this page choose "Voir tout" next to " Historique d'achat", then the label for each completed checkout has an id "Commande #1020304".
Accessing the URL https://www.izneo.com/fr/panier-fini/1020304 will show you the checkout completion page.

My use case is I download the albums after each checkout.
Sometimes I can have albums from the same series in different checkouts.
It is easier for me to download per checkout to avoid downloading the albums from the previous checkouts from the series page via izneo_list.py.

Si tu préfère queue l'on continue en français je veux bien. Après tout izneo n'a plus d'interface en anglais malheureusement.

**Comment by izneo-get** [comment]
Ca ne fonctionne pas chez moi. 
Quand je regarde la liste de mes commandes et que je copie / colle le numéro de commande, j'obtiens une page sans aucune information.
image
image

**Comment by prahal** [comment]
@izneo-get une typo de ma part. C'est fr/panier-fin/<id> pas fr/panier-fini/<id> (noter le panier-fin et non panier-fini
Du coup il faut mettre à jour le commentaire dans la push request :-/
Je vais essayer de caser cela. Pouvez vous confirmer que avec "panier-fin" cela marche ?

**Comment by izneo-get** [comment]
C'est bon, avec la bonne URL ça fonctionne 👍

**Pull request merged**
